ARG BASE_IMAGE_TAG=ltsc2019

FROM mcr.microsoft.com/windows/servercore:${base_image_tag}

ARG BASE_IMAGE_TAG=ltsc2019

SHELL ["powershell", "-Command"]

USER ContainerAdministrator

WORKDIR C:\\app

# CVE-2013-3900: enable strict PE signature padding validation
RUN reg add "HKLM\Software\Microsoft\Cryptography\Wintrust\Config" /v EnableCertPaddingCheck /t REG_SZ /d 1 /f
RUN reg add "HKLM\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config" /v EnableCertPaddingCheck /t REG_SZ /d 1 /f

COPY bin\\nri-kubernetes-windows-${BASE_IMAGE_TAG}-amd64.exe "C:\\app\\nri-kubernetes.exe"

ENTRYPOINT ["C:\\app\\nri-kubernetes.exe"]
