# Chart linter defaults to `master` branch so we need to specify this as the default branch
# or `cl` will fail with a not-so-helpful error that says:
# "Error linting charts: Error identifying charts to process: Error running process: exit status 128"
target-branch: main
