run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor

linters:
  enable:
    - unused      # replaces deprecated deadcode
    - errcheck
    - gofmt
    - revive      # replaces deprecated golint
    - goimports
    - govet
    - gosimple
  enable-all: false
  disable-all: true
