run:
  skip-dirs:
    - vendor

linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - golint
    - goimports
    - govet
    - interfacer
    - gosimple
  enable-all: false
  disable-all: true
