FROM alpine:latest

ADD --chmod=755 bin/nri-kubernetes-linux-amd64-scraper /var/db/newrelic-infra/newrelic-integrations/bin/

ENTRYPOINT ["/var/db/newrelic-infra/newrelic-integrations/bin/nri-kubernetes-linux-amd64-scraper"]
