FROM alpine:3.8

WORKDIR /var/db/newrelic-infra/fsi

ENV HELM_LATEST_VERSION="v2.9.1"

RUN apk add --update ca-certificates \
 && apk add --update -t deps wget \
 && wget https://storage.googleapis.com/kubernetes-helm/helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz \
 && tar -xvf helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz \
 && mv linux-amd64/helm /usr/local/bin \
 && apk del --purge deps \
 && rm /var/cache/apk/* \
 && rm -f /helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz

COPY ./bin/nri-kubernetes-e2e nri-kubernetes-e2e
COPY e2e/schema e2e/schema
COPY e2e/charts e2e/charts

ENTRYPOINT ["/var/db/newrelic-infra/fsi/nri-kubernetes-e2e"]
