{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depl
spec:
  paused: false
  minReadySeconds: 6
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: busybox
          image: busybox
          args:
            - sleep
            - infinity
          volumeMounts:
            {{- if .Values.persistentVolumeClaim.enabled }}
            - mountPath: /pv
              name: pv-storage
            {{- end }}
            - mountPath: /emptydir
              name: an-empty-dir
      volumes:
        {{- if .Values.persistentVolumeClaim.enabled }}
        - name: pv-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pv-claim
        {{- end }}
        - name: an-empty-dir
          emptyDir:
            sizeLimit: 128Mi
{{- end }}
