{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  paused: false
  minReadySeconds: 6
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: compute-pi-digits
          image: perl:5.34.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 40m
              memory: 15Mi
            limits:
              cpu: 80m
              memory: 30Mi
          command:
          - perl
          - -Mbignum=bpi
          - -wle
          - while (true) { open(FH, '>', './{{ .Values.fileSystemTest.fileName }}') or die "Cannot open file - $!"; print FH bpi(100); close(FH); print bpi(2700) }
          volumeMounts:
            - mountPath: /output
              name: storage
        {{- if .Values.demo.enabled }}
        - name: failing-container
          image: docker.io/library/bash:5
          command: ["bash"]
          args:
          - -c
          - echo "Hello world! I'm going to exit with 42 to simulate a software bug." && sleep 300 && exit 42
        {{- end }}
      volumes:
        - name: storage
          emptyDir:
            sizeLimit: 30Mi
{{- end }}
