{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5M
  hostPath:
    path: /data/pv0001/
{{- end }}
