{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-storage
spec:
  storageClassName: {{ .Release.Name }}-pv-class
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  hostPath:
    path: /data/pv/
    type: DirectoryOrCreate
{{- end }}
