{{- if .Values.pending.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-container-creating
  labels:
    app: creating
spec:
  containers:
    - name: alpine
      image: alpine:3.22.1
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          # Force a 'CreateContainerError':
          # 'Error response from daemon: Minimum memory limit allowed is 6MB'
          memory: 5M
          cpu: 5m
        requests:
          memory: 5M
          cpu: 5m
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-container-pending
  labels:
    app: pending
    environment: dev
    team: k8-team
  annotations:
    owner: "pod@example.com"
    description: "pod for e2e workloads"
spec:
  containers:
    - name: alpine
      image: alpine:3.22.1
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  nodeSelector:
    not-existing: not-existing
{{- end }}
