{{- if .Values.windows.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: windows-server-2019
    labels:
        app: windows-server-2019
spec:
    replicas: 1
    selector:
        matchLabels:
            app: windows-server-2019
    template:
        metadata:
            labels:
                app: windows-server-2019
        spec:
            nodeSelector:
                kubernetes.io/os: windows
            tolerations: 
                - key: "os"
                  operator: "Equal"
                  value: "windows"
                  effect: "NoSchedule"
            containers:
                - name: windows-server-2019
                  image: mcr.microsoft.com/windows/servercore:ltsc2019
                  resources:
                    requests:
                        cpu: "1" 
                        memory: "2Gi"
                    limits:
                        cpu: "2"
                        memory: "4Gi"
                  command:
                    - powershell
                    - " -Command"
                    - |
                      while ($true) {
                        Write-Host "Random Text: $(Get-Random)";
                        Start-Sleep -Seconds 3600;
                      }
{{- end }}