{{- if and .Values.statefulSet.enabled .Values.windows.is2019 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nriKubernetes.e2e.kubelet.fullname.windows2019" .}}-statefulset
  labels:
    app: statefulset-w-2019
spec:
  selector:
    app: statefulset-w-2019
  ports:
    - port: 8090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nriKubernetes.e2e.kubelet.fullname.windows2019" .}}-statefulset
spec:
  serviceName: statefulset-w-2019
  replicas: 1
  selector:
    matchLabels:
      app: statefulset-w-2019
  template:
    metadata:
      labels:
        app: statefulset-w-2019
    spec:
      nodeSelector:
        kubernetes.io/os: windows
        node.kubernetes.io/windows-build: 10.0.17763
      tolerations:
        - key: "node.kubernetes.io/os"
          operator: "Equal"
          value: "windows"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/windows-build"
          operator: "Equal"
          value: "10.0.17763"
          effect: "NoSchedule"
      containers:
        - name: random-text
          image: mcr.microsoft.com/windows/servercore:ltsc2019
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "200Mi"
          command:
            - powershell
            - " -Command"
            - |
              while ($true) {
                Write-Host "Random Text: $(Get-Random)";
                Start-Sleep -Seconds 10;
              }
{{- end }}
---
{{- if and .Values.statefulSet.enabled .Values.windows.is2022 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nriKubernetes.e2e.kubelet.fullname.windows2022" .}}-statefulset
  labels:
    app: statefulset-w-2022
spec:
  selector:
    app: statefulset-w-2022
  ports:
    - port: 8091
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nriKubernetes.e2e.kubelet.fullname.windows2022" .}}-statefulset
spec:
  serviceName: statefulset-w-2022
  replicas: 1
  selector:
    matchLabels:
      app: statefulset-w-2022
  template:
    metadata:
      labels:
        app: statefulset-w-2022
    spec:
      nodeSelector:
        kubernetes.io/os: windows
        node.kubernetes.io/windows-build: 10.0.20348
      tolerations:
        - key: "node.kubernetes.io/os"
          operator: "Equal"
          value: "windows"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/windows-build"
          operator: "Equal"
          value: "10.0.20348"
          effect: "NoSchedule"
      containers:
        - name: random-text
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "200Mi"
          command:
            - powershell
            - " -Command"
            - |
              while ($true) {
                Write-Host "Random Text: $(Get-Random)";
                Start-Sleep -Seconds 10;
              }
{{- end }}
