{{- if and (.Values.controlPlane.enabled) (.Values.rbac.create) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "common.naming.fullname" . }}-controlplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.naming.fullname" . }}-controlplane
subjects:
  - kind: ServiceAccount
    name: {{ include "common.serviceAccount.name" . }}-controlplane
    namespace: {{ .Release.Namespace }}
{{- end -}}
