{{- if .Values.rbac.create }}
{{- $namespaces := (include "newrelic.roleBindingNamespaces" . | fromYaml) -}}
{{- range $namespaces.roleBindingNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "newrelic.common.labels" $ | nindent 4 }}
  name: {{ include "newrelic.common.naming.fullname" $ }}-{{ . }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "newrelic.common.naming.fullname" $ }}-secrets
subjects:
- kind: ServiceAccount
  name: {{ include "newrelic.common.serviceAccount.name" $ }}-controlplane
  namespace: {{ $.Release.Namespace }}
{{- end -}}
{{- end }}
