apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-02T23:13:42Z"
    labels:
      kubernetes.io/metadata.name: default
    name: default
    resourceVersion: "9"
    uid: c19c202e-1b63-42ed-837d-a55e69bd865c
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-02T23:13:42Z"
    labels:
      kubernetes.io/metadata.name: kube-node-lease
    name: kube-node-lease
    resourceVersion: "18"
    uid: cbb51ccf-14a4-40a3-83c6-a78db02a8067
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-02T23:13:42Z"
    labels:
      kubernetes.io/metadata.name: kube-public
    name: kube-public
    resourceVersion: "6"
    uid: 219d0810-01a4-489e-90b0-8ecff18d3a8e
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-02T23:13:42Z"
    labels:
      kubernetes.io/metadata.name: kube-system
    name: kube-system
    resourceVersion: "3"
    uid: 1950d186-c7ba-4a71-9cf4-27ef466e27bd
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      description: Namespace for e2e workloads
      meta.helm.sh/release-name: e2e
      meta.helm.sh/release-namespace: scraper
      owner: namespace@example.com
    creationTimestamp: "2026-02-02T23:14:46Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      environment: dev
      kubernetes.io/metadata.name: nri-test-namespace
      team: k8-team
    name: nri-test-namespace
    resourceVersion: "540"
    uid: 966b962a-e232-47e9-9521-61c1daea71a4
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-02T23:14:46Z"
    labels:
      kubernetes.io/metadata.name: scraper
      name: scraper
    name: scraper
    resourceVersion: "536"
    uid: 149ac897-f4d7-417e-b25d-54f05c1797ca
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
kind: List
metadata:
  resourceVersion: ""
