apiVersion: v1
kind: Service
metadata:
  name: statefulset-{{ .Release.Name }}
  labels:
    app: statefulset
spec:
  selector:
    app: statefulset
  ports:
    - port: 8089
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-{{ .Release.Name }}
spec:
  serviceName: statefulset
  replicas: 2
  selector:
    matchLabels:
      app: statefulset
  template:
    metadata:
      labels:
        app: statefulset
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
          - sleep
          - infinity
