apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-container-creating
spec:
  containers:
  - name: alpine
    image: alpine:3.7
    resources:
      limits:
        memory: 5M
        cpu: 5m
      requests:
        memory: 5M
        cpu: 5m
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pending
spec:
  containers:
    - name: alpine
      image: alpine:3.7
  nodeSelector:
    not-existing: not-existing
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stateful-set
  labels:
    app: statefulset
spec:
  selector:
    app: statefulset
  ports:
    - port: 8089
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-stateful-set
spec:
  serviceName: statefulset
  replicas: 2
  selector:
    matchLabels:
      app: statefulset
  template:
    metadata:
      labels:
        app: statefulset
    spec:
      containers:
        - name: busybox
          image: busybox
          args:
            - sleep
            - infinity
