apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-container-creating
spec:
  containers:
  - name: alpine
    image: alpine:latest
    resources:
      limits:
        memory: 5M
        cpu: 5m
      requests:
        memory: 5M
        cpu: 5m
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pending
spec:
  containers:
    - name: alpine
      image: alpine:latest
  nodeSelector:
    not-existing: not-existing
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stateful-set
  labels:
    app: statefulset
spec:
  selector:
    app: statefulset
  ports:
    - port: 8089
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-stateful-set
spec:
  serviceName: statefulset
  replicas: 2
  selector:
    matchLabels:
      app: statefulset
  template:
    metadata:
      labels:
        app: statefulset
    spec:
      containers:
        - name: busybox
          image: busybox
          args:
            - sleep
            - infinity
---
{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5M
  hostPath:
    path: /data/pv0001/
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hpa
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: k8s.gcr.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hpa
  labels:
    run: php-apache
spec:
  ports:
    - port: 80
  selector:
    run: php-apache
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-hpa
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
