apiVersion: v2
version: 1.2.0
appVersion: "1.0.0"
description: This chart creates e2e resources for nri-kubernetes.
name: e2e-resources

dependencies:
  - name: kube-state-metrics
    version: 2.13.2
    repository: https://kubernetes.github.io/kube-state-metrics

maintainers:
  - name: alvarocabanas
    url: https://github.com/alvarocabanas
  - name: carlossscastro
    url: https://github.com/carlossscastro
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
  - name: roobre
    url: https://github.com/roobre
