{{- if .Values.kubelet.enabled -}}
{{- if .Values.customAttributes | kindIs "string" }}
{{- fail ( include "newrelic.compatibility.message.customAttributes" . ) -}}
{{- else -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "common.naming.fullname" . }}-agent-kubelet
data:
  newrelic-infra.yml: |-
    # This is the configuration file for the infrastructure agent. See:
    # https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
    {{- include "nriKubernetes.kubelet.agentConfig" . | nindent 4 }}
{{- end -}}
{{- end -}}
