---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
  name: {{ include "nriKubernetes.kubelet.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  nri-kubernetes.yml: |
    {{- (merge .Values.common.config (include "newrelic.integrationConfigDefaults" . | fromYaml)) | toYaml | nindent 4 }}
    operator:
      enabled:  true
