apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2023-11-10T01:44:30Z"
    labels:
      endpointslice.kubernetes.io/skip-mirror: "true"
    name: kubernetes
    namespace: default
    resourceVersion: "197"
    uid: cf0eabe5-9494-4709-a0b7-1c6e35696509
  subsets:
  - addresses:
    - ip: 192.168.49.2
    ports:
    - name: https
      port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"datagen-1-28_0b82988e-ae08-479f-9de6-f79ce5e0a4b0","leaseDurationSeconds":15,"acquireTime":"2023-11-10T01:45:15Z","renewTime":"2023-11-10T01:47:04Z","leaderTransitions":0}'
    creationTimestamp: "2023-11-10T01:45:15Z"
    name: k8s.io-minikube-hostpath
    namespace: kube-system
    resourceVersion: "898"
    uid: 3ffdcead-4cca-4c24-b498-c3e7d1f4d50f
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-11-10T01:44:59Z"
    creationTimestamp: "2023-11-10T01:44:44Z"
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
    name: kube-dns
    namespace: kube-system
    resourceVersion: "384"
    uid: 0a2311c4-8667-4b31-a732-6d8d6bba4f6f
  subsets:
  - addresses:
    - ip: 10.244.0.2
      nodeName: datagen-1-28
      targetRef:
        kind: Pod
        name: coredns-5dd5756b68-hgq9s
        namespace: kube-system
        uid: afcfabc6-df62-49e8-9d64-39b2326af660
    ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: dns
      port: 53
      protocol: UDP
    - name: metrics
      port: 9153
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-11-10T01:45:04Z"
    creationTimestamp: "2023-11-10T01:45:00Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: metrics-server
      kubernetes.io/minikube-addons: metrics-server
      kubernetes.io/minikube-addons-endpoint: metrics-server
      kubernetes.io/name: Metrics-server
    name: metrics-server
    namespace: kube-system
    resourceVersion: "433"
    uid: b6c70375-d7bf-4dca-815b-6de500c48b14
  subsets:
  - addresses:
    - ip: 10.244.0.3
      nodeName: datagen-1-28
      targetRef:
        kind: Pod
        name: metrics-server-7c66d45ddc-f44hs
        namespace: kube-system
        uid: 06a46388-4411-447d-af4f-f44f3d4830e7
    ports:
    - name: https
      port: 4443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-11-10T01:46:03Z"
    creationTimestamp: "2023-11-10T01:45:07Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      run: php-apache
    name: e2e-hpa
    namespace: scraper
    resourceVersion: "670"
    uid: 4a1e2bee-06fb-4e01-8bfb-f79aee3f932c
  subsets:
  - addresses:
    - ip: 10.244.0.5
      nodeName: datagen-1-28
      targetRef:
        kind: Pod
        name: e2e-hpa-97d79d4cd-pc2kl
        namespace: scraper
        uid: 01fd9a25-63a8-406c-b7f7-a37a30b90e4c
    ports:
    - port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-11-10T01:46:17Z"
    creationTimestamp: "2023-11-10T01:45:07Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: e2e
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.10.0
      helm.sh/chart: kube-state-metrics-5.12.1
    name: e2e-kube-state-metrics
    namespace: scraper
    resourceVersion: "721"
    uid: a8909b73-e736-4225-bf4e-355b62fccf18
  subsets:
  - addresses:
    - ip: 10.244.0.6
      nodeName: datagen-1-28
      targetRef:
        kind: Pod
        name: e2e-kube-state-metrics-86f7c9c6bb-qscbn
        namespace: scraper
        uid: 4d9451b9-cc1c-4724-be59-80a7726bb36b
    ports:
    - name: http
      port: 8080
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-11-10T01:46:32Z"
    creationTimestamp: "2023-11-10T01:45:07Z"
    labels:
      app: statefulset
      app.kubernetes.io/managed-by: Helm
    name: e2e-statefulset
    namespace: scraper
    resourceVersion: "810"
    uid: 10199445-443f-400c-b41b-77433a1861d4
  subsets:
  - addresses:
    - ip: 10.244.0.12
      nodeName: datagen-1-28
      targetRef:
        kind: Pod
        name: e2e-statefulset-0
        namespace: scraper
        uid: 46071d46-6af2-4141-b4ea-1667fc0cb4f4
    - ip: 10.244.0.14
      nodeName: datagen-1-28
      targetRef:
        kind: Pod
        name: e2e-statefulset-1
        namespace: scraper
        uid: 03c7aa49-762e-4506-b961-73980a98ef1a
    ports:
    - port: 8089
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
