# This action requires that any PR targeting the main branch should touch at
# least one CHANGELOG file. If a CHANGELOG entry is not required, add the "Skip
# Changelog" label to disable this action.

name: changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog')}}

    steps:
      - uses: actions/checkout@v3

      - name: Check for CHANGELOG file changes
        run: |
          # Only the latest commit of the feature branch is available
          # automatically. To diff with the base branch, we need to
          # fetch that too (and we only need its latest commit).
          git fetch origin ${{ github.base_ref }} --depth=1
          if [[ $(git diff --name-only FETCH_HEAD | grep CHANGELOG) ]]
          then
            echo "The CHANGELOG file was modified. Looks good!"
          else
            echo "The CHANGELOG file was not modified."
            echo "Please add a CHANGELOG entry to the appropriate header under \"Unreleased\" , or add the \"Skip Changelog\" label if not required."
            false
          fi

  lint-changelog:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for unordered list in changelog
        run: |
          if grep -E "^\s*-\s" ./CHANGELOG.md; then
            echo "Changelog is valid: Unordered list items found."
          else
            echo "Changelog is invalid: No unordered list items found."
            exit 1
          fi