name: Release newrelic-infrastructure chart
on:
  push:
    branches:
      - main

jobs:
  release-chart:
    permissions:
      contents: write
    uses: newrelic/k8s-agents-automation/.github/workflows/reusable-release-chart.yml@main
    secrets:
      gh_token: "${{ secrets.GITHUB_TOKEN }}"
      slack_channel: ${{ secrets.K8S_AGENTS_SLACK_CHANNEL }}
      slack_token: ${{ secrets.K8S_AGENTS_SLACK_TOKEN }}
