name: Security Scan

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  trivy:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    uses: newrelic/k8s-agents-automation/.github/workflows/reusable-security.yaml@main
    secrets:
      slack_channel: ${{ secrets.K8S_AGENTS_SLACK_CHANNEL }}
      slack_token: ${{ secrets.K8S_AGENTS_SLACK_TOKEN }}
