name: Test Needs Variations

on:
  workflow_dispatch:
  push:
    branches:
      - testZgha


jobs:
  job_a:
    runs-on: ubuntu-latest
    outputs:
      boolean_output: ${{ steps.echo_job_a.outputs.boolean_output }}
    steps:
      - name: Echo from Job A
        run: echo "This is Job A"
      - name: Set output for Job A
        id: echo_job_a
        run: echo "boolean_output=true" >> $GITHUB_OUTPUT

  job_b:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Job B
        run: echo "This is Job B"

  job_a2:
    runs-on: ubuntu-latest
    needs: job_a
    if: ${{ always() && needs.job_a.outputs.boolean_output == 'true' }}
    steps:
      - name: Echo from Job A2
        run: echo "This is Job A2 (needs job_a, always runs if job_a output is true)"

  job_c:
    runs-on: ubuntu-latest
    needs: [ job_b ]
    steps:
      - name: Echo from Job C
        run: echo "This is Job C (needs job_b)"

  job_d:
    runs-on: ubuntu-latest
    needs: [ job_a2, job_c ]
    steps:
      - name: Echo from Job D
        run: echo "This is Job D (needs job_a and job_c)"

  job_skip:
    runs-on: ubuntu-latest
    needs: [ job_a2, job_c ]
    if: ${{ always() && needs.job_a.outputs.boolean_output == 'false' }}
    steps:
      - name: Echo from Job Skip
        run: echo "This is Job Skip (needs job_a and job_c, runs only if job_a output is false)"

  job_e:
    runs-on: ubuntu-latest
    needs: [ job_a2, job_c, job_skip ]
    steps:
      - name: Echo from Job E
        run: echo "This is Job E (needs job_a and job_b, always runs if job_a output is true)"
