name: E2E on EKS

on:
  workflow_dispatch:
  push:
    branches:
      - testEKSe2e*

permissions:
  id-token: write
  contents: read

jobs:
  create-windows-image:
    uses: "newrelic/nri-kubernetes/.github/workflows/build-windows-integration-test.yml@testEKSe2e"
    with:
      windows_directory: ${{ github.workspace }}
      docker_image_name: newrelic/nri-kubernetes-internal
    secrets:
      K8S_AGENTS_DOCKERHUB_USERNAME: ${{ secrets.K8S_AGENTS_DOCKERHUB_USERNAME }}
      K8S_AGENTS_DOCKERHUB_TOKEN: ${{ secrets.K8S_AGENTS_DOCKERHUB_TOKEN }}
  e2e:
    needs: create-windows-image
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4 
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.K8S_AWS_ACCOUNT_ID }}:role/${{ secrets.K8S_AWS_GHA_ROLE_TEST }}
          aws-region: us-west-1
          role-session-name: gha-e2e-test-session
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name tnguyen-bubbles --region us-west-1
      - name: Verify cluster access
        run: |
          kubectl get nodes
      - name: Echo output from build-windows-integration-test
        run: |
            echo "Output from build-windows-integration-test: ${{ needs.create-windows-image.outputs.result }}"
